# Generated by Django 4.2.3 on 2023-07-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=200, null=True)),
                ('course_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.FloatField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now=True, null=True)),
                ('preferred_exam_date', models.DateTimeField(blank=True, null=True)),
                ('exam_status', models.FloatField(blank=True, null=True)),
                ('application_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
