# Generated by Django 4.2.3 on 2023-07-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='exam_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='payment_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
